- name: Create 'registry.docker-registry' directory in docker certs.d
  file:
    path: "/etc/docker/certs.d/registry.docker-registry"
    state: directory
    recurse: true

- name: Create 'registry.docker-registry' directory in containerd certs.d
  file:
    path: "/etc/containerd/certs.d/registry.docker-registry"
    state: directory
    recurse: true

- name: Create the hosts.toml file for registry.docker-registry in containerd
  copy:
    dest: /etc/containerd/certs.d/registry.docker-registry/hosts.toml
    content: |
      server = "https://registry.docker-registry"
      [host."https://registry.docker-registry"]
        ca = "/etc/containerd/certs.d/registry.docker-registry/ca.crt"
  notify: restart containerd

- name: Set containerd registry config_path
  replace:
    path: /etc/containerd/config.toml
    regexp: '\[plugins\."io\.containerd\.grpc\.v1\.cri"\.registry]\s*\n+(\s*)config_path\s*=.*'
    replace: '[plugins."io.containerd.grpc.v1.cri".registry]\n\1config_path = "/etc/containerd/certs.d"'
  notify: restart containerd
