---
- name: Copy the CA certificate to docker certs.d/registry.docker-registry directory
  copy:
    src: /opt/docker_registry/certs/domain.crt
    dest: /etc/docker/certs.d/registry.docker-registry/ca.crt

- name: Copy the CA certificate to containerd certs.d/registry.docker-registry directory
  copy:
    src: /opt/docker_registry/certs/domain.crt
    dest: /etc/containerd/certs.d/registry.docker-registry/ca.crt
