---
- name: Create 'registry.docker-registry' directory in docker certs.d
  file:
    path: "/etc/docker/certs.d/registry.docker-registry"
    state: directory
    recurse: true

- name: Copy the CA certificate to docker certs.d/registry.docker-registry directory
  copy:
    src: /opt/docker_registry/certs/domain.crt
    dest: /etc/docker/certs.d/registry.docker-registry/ca.crt

- name: Create 'registry.docker-registry' directory in containerd certs.d
  file:
    path: "/etc/containerd/certs.d/registry.docker-registry"
    state: directory
    recurse: true

- name: Copy the CA certificate to containerd certs.d/registry.docker-registry directory
  copy:
    src: /opt/docker_registry/certs/domain.crt
    dest: /etc/containerd/certs.d/registry.docker-registry/ca.crt
