---
- name: Create docker-registry namespace
  block:
    - copy: src=registry-namespace.yml dest=/tmp/registry-namespace.yml
    - command: kubectl apply -f /tmp/registry-namespace.yml

- name: Create SSL key and certificate
  include: "ssl.yml"
  when: enable_secure

- name: Create htpasswd file and secret to store credentials
  include: "auth.yml"
  when: enable_auth

- name: Create Persistent Volume Claim
  block:
    - copy: src=registry-pvc.yml dest=/tmp/registry-pvc.yml
    - command: kubectl apply -f /tmp/registry-pvc.yml

- name: Create deployment
  block:
    - template: src=registry-deployment.j2 dest=/tmp/registry-deployment.yml
    - command: kubectl apply -f /tmp/registry-deployment.yml

- name: Create Service
  block:
    - template: src=registry-svc.j2 dest=/tmp/registry-svc.yml
    - command: kubectl apply -f /tmp/registry-svc.yml