---
- name: Include "{{type_of_node}}" tasks
  include: "{{type_of_node}}.yml"

- name: Get service ClusterIP
  command: kubectl get svc registry -n docker-registry -o=jsonpath='{.spec.clusterIP}'
  register: registry_ip

- name: Add service name and IP to /etc/hosts file in all nodes
  lineinfile:
    dest: /etc/hosts
    line: '{{ registry_ip.stdout }} registry.docker-registry'
  when: enable_secure