apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pv-claim
  namespace: docker-registry
spec:
  selector:
    matchLabels:
      app: registry
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
